### ISSUE TITLE
one column of data does not work with two layers (i.e. two exports)

### ISSUE THREAD

**Issue by fnaji** [tercen/export_crosstab_shiny_operator#3]

**Comment by fnaji** [comment]
The example is 
https://tercen.com/pamgene/w/7f865df18753ebf56ca2bbafe1d3fde5/ds/068a218b-ddeb-43f0-b8d2-d86bd69dd249/wa

**Comment by ginberg** [comment]
@fnaji the link does not work anymore, can you update it?

**Comment by ginberg** [comment]
@fnaji for me it seems to work, see https://tercen.com/pamgene/w/23b21660af25b35da6cfefe0eaaa161c
This is the situation you are describing right?
