### ISSUE TITLE
Export to database

### ISSUE THREAD

**Issue by ginberg** [tercen/export_crosstab_shiny_operator#6]
According to the excelsheet, there should be an option to export to database.
Savi: "Export to Db means Export to Repository/ ServerDB. This is located locally or on PamGene server. We use this only for Export after the image analysis, so that we can import it back through Import function.
I think that in Tercen this is et-up differently. Please talk to Alex/ Faris."

How can we do this in Tercen? Any idea @fnaji @amaurel ?

**Comment by fnaji** [comment]
No. Currently not possible.

**Comment by ginberg** [comment]
closing since we are not going to do this
